version: '3'

includes:
  test: ./taskfiles/Tests.yml
  build: ./taskfiles/Build.yml
  docker: ./taskfiles/Docker.yml
  tools: ./taskfiles/Tools.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  verify:
    desc: Run all verification checks (test, lint, build)
    cmds:
      - task tools:tidy
      - task tools:fmt
      - task tools:lint
      - task test:default
      - task build:default

  ci:
    desc: Run all CI checks
    cmds:
      - task tools:tidy
      - task tools:fmt
      - task tools:lint
      - task test:default
      - task build:examples

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f coverage.out coverage.html
      - go clean ./...
